/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package curisemanagement;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author amrbh
 */
public class Ticket extends javax.swing.JFrame {
    Connection con,conn;
    ResultSet rs;
    int a;
    CallableStatement cstmt,cs,cs1;
    PreparedStatement ps,pst,pst1,pst2,pst3,pst4;
    /**
     * Creates new form Ticket
     */
    public Ticket() {
         con=connectdb.connectdb();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        cruiseid = new javax.swing.JTextField();
        routeid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        nationality = new javax.swing.JTextField();
        pno = new javax.swing.JTextField();
        tdate = new javax.swing.JTextField();
        tickets = new javax.swing.JTextField();
        rooms = new javax.swing.JTextField();
        fare = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOOK TICKETS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 10, 300, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(201, 55, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cruise ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(201, 103, 142, 33);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Route ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(201, 154, 142, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(201, 199, 160, 35);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nationality");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 240, 142, 33);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 290, 142, 31);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Travel Date");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(201, 329, 142, 31);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("No of Tickets");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(201, 378, 142, 35);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("No of rooms");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(201, 420, 142, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Total Fare");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(200, 560, 142, 28);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SEE TOTAL FARE AND BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 520, 240, 35);

        jButton3.setText("Back to Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 610, 114, 49);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(478, 59, 150, 22);
        getContentPane().add(cruiseid);
        cruiseid.setBounds(478, 108, 150, 22);
        getContentPane().add(routeid);
        routeid.setBounds(478, 161, 150, 20);
        getContentPane().add(name);
        name.setBounds(480, 210, 150, 22);
        getContentPane().add(nationality);
        nationality.setBounds(480, 250, 150, 22);
        getContentPane().add(pno);
        pno.setBounds(480, 290, 150, 22);
        getContentPane().add(tdate);
        tdate.setBounds(480, 330, 150, 22);
        getContentPane().add(tickets);
        tickets.setBounds(480, 380, 150, 22);
        getContentPane().add(rooms);
        rooms.setBounds(485, 420, 150, 20);

        fare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fareActionPerformed(evt);
            }
        });
        getContentPane().add(fare);
        fare.setBounds(480, 560, 145, 28);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mode of payment");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(200, 470, 190, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit card", "Debit card", "Net banking", "UPI", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(483, 466, 145, 22);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aravind\\Desktop\\nini\\b9c8f893c9a782033a01f47e0c0b1d6e.jpg")); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-20, 0, 880, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
             int jml = Integer.parseInt(tickets.getText());
             cs=con.prepareCall("{?=call check_ticket_availability(?,?)}");
             cs.setString(2,cruiseid.getText());
             cs.setInt(3,jml);
             cs.registerOutParameter(1,Types.INTEGER);
             cs.execute();
             int flag=cs.getInt(1);
               int room = Integer.parseInt(rooms.getText());
            cs=con.prepareCall("{?=call check_rooms_availability(?,?)}");
             cs.setString(2,cruiseid.getText());
             cs.setInt(3,room);
             cs.registerOutParameter(1,Types.INTEGER);
             cs.execute();
             int flagroom=cs.getInt(1);

             if(flag==0 && flagroom==0){
             
              ps=con.prepareStatement("insert into booking(custid,cruiseid,routeid,name,nationality,phone,from_date,no_of_tickets,no_of_rooms) values(?,?,?,?,?,?,?,?,?)");
              ps.setString(1,id.getText());
              ps.setString(2,cruiseid.getText());
              ps.setString(3,routeid.getText());
              ps.setString(4,name.getText());
              ps.setString(5,nationality.getText());
              ps.setString(6,pno.getText());
              ps.setString(7,tdate.getText());
              ps.setString(8,tickets.getText());
              ps.setString(9,rooms.getText());
              rs=ps.executeQuery();
              cstmt=con.prepareCall("{?=call calculate_fare(?,?,?,?)}");//changes made here
              String b=cruiseid.getText();
              String c=routeid.getText();
              cstmt.setInt(4,jml);
              cstmt.setString(2,b);
              cstmt.setString(3,c);
              cstmt.setString(5,id.getText());//changes made here
              cstmt.registerOutParameter(1,Types.INTEGER);
              cstmt.execute();
              String a=cstmt.getString(1);
              fare.setText(a);
              pst=con.prepareStatement("call decrease_tickets_and_rooms(?,?,?)");
              pst.setString(1,b);
              pst.setInt(2,jml);
              pst.setInt(3,room);
              rs=pst.executeQuery();
              JOptionPane.showMessageDialog(null, "Tickets Booked.Have a wonderful journey");
               
             }
             else
             {
                 if(flag!=0)
                      JOptionPane.showMessageDialog(null, "Sorry,not enough tickets");
                 else  
                      JOptionPane.showMessageDialog(null, "Sorry,not enough rooms");
                
                 
             }
                  } catch (SQLException ex) {
              Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fareActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        useroptions u=new useroptions();
        u.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cruiseid;
    private javax.swing.JTextField fare;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nationality;
    private javax.swing.JTextField pno;
    private javax.swing.JTextField rooms;
    private javax.swing.JTextField routeid;
    private javax.swing.JTextField tdate;
    private javax.swing.JTextField tickets;
    // End of variables declaration//GEN-END:variables
}
