/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package curisemanagement;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author arun
 */
public class ticket_cancel extends javax.swing.JFrame {
    Connection con,conn;
    ResultSet rs,rs1,rs2,rst;
    int a;
    CallableStatement cstmt,cs,cs1;    
    PreparedStatement ps,ps1,ps2,pst,pst1,pst2,pst3,pst4;
    
    /**
     * Creates new form ticket_cancel
     */
    public ticket_cancel() {
         con=connectdb.connectdb();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cuID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        check = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Cancel   tickets   ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 30, 360, 49);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer  ID ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(87, 147, 155, 30);

        cuID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuIDActionPerformed(evt);
            }
        });
        getContentPane().add(cuID);
        cuID.setBounds(284, 149, 140, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Delete ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 290, 150, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 280, 120, 41);

        check.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        check.setText("check ticket");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        getContentPane().add(check);
        check.setBounds(466, 149, 160, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aravind\\Desktop\\nini\\b9c8f893c9a782033a01f47e0c0b1d6e.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 0, 670, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
             String customer_id = cuID.getText();
                pst=con.prepareStatement("call cancel_ticket(?)");
              pst.setString(1,customer_id);
                rst=pst.executeQuery();
 
            PreparedStatement ps1=con.prepareStatement("delete from booking  where custid= ? ");
            ps1.setString(1,customer_id);
              rs1=ps1.executeQuery();
             JOptionPane.showMessageDialog(this," The tickets have been deleted successfully");
        }
         catch (SQLException ex) {
              Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
         }
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cuIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        useroptions up2=new useroptions();
        up2.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
         try {
              PreparedStatement ps2=con.prepareStatement("select custid from booking where custid = ?");
              ps2.setString(1,cuID.getText());
              rs2=ps2.executeQuery();
              if(rs2.next())
              {
              JOptionPane.showMessageDialog(null, " Tickets for this  ID Found!!");
              }else
              {
              JOptionPane.showMessageDialog(null, " Tickets for this  ID Not Found!!");
              }
              // TODO add your handling code here:
          } catch (SQLException ex) {
              Logger.getLogger(login_register.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticket_cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticket_cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticket_cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticket_cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticket_cancel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check;
    private javax.swing.JTextField cuID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
